### ISSUE TITLE
Aborted Sequence Assembly

### ISSUE THREAD

**Issue by helena-shapton** [kew-myco/its_glue#11]
All sequences were aborted in assembly stage.
![image](https://user-images.githubusercontent.com/66360941/163710995-a9de895c-f034-433b-9c30-dbc85a8aabc9.png)

Attached are the log files as requested.
[its_sing_log.txt](https://github.com/kew-myco/its_glue/files/8501397/its_sing_log.txt)
[cons_log.txt](https://github.com/kew-myco/its_glue/files/8501398/cons_log.txt)
[its_cons_log.txt](https://github.com/kew-myco/its_glue/files/8501399/its_cons_log.txt)

**Comment by blex-max** [comment]
Checking the logs, 68 sequences were successfully assembled, and then Tracy (the basecalling tool) starts throwing errors. I'm not sure why that is - I will investigate/ask the Tracy team. Then subsequently there appears to be an error in the pipeline when it tries to tidy up the results of ITSx, which I will try to fix ASAP. By the way, were the bug/help report templates unavailable when you submitted this issue?

**Comment by blex-max** [comment]
On further inspection I see that the problem with the pipeline isn't a bug - you need to run the command from the top level directory, i.e. `its_glue`, not from `its_glue/scripts`. In the future I'll try to make the pipeline more 'location agnostic' but for now that's the solution!

**Comment by blex-max** [comment]
could you please upload `005_H12-r.ab1` and `005_H12-f.ab1` so I can investigate the basecalling failure? You might have to put them in a zip first.

**Comment by helena-shapton** [comment]
Okay I ran from it_glue and the pipeline was able to sort the results with caveat being that they were all still aborted 
![image](https://user-images.githubusercontent.com/66360941/163718380-e81e411c-304f-449d-86b6-25f51d626efb.png)
[005_H12-f - Copy.zip](https://github.com/kew-myco/its_glue/files/8501790/005_H12-f.-.Copy.zip)

**Comment by blex-max** [comment]
From the logs it would appear that 1/3 of the assemblies are successful - so you are getting some results if you check the output folders! Everything labelled 003 assembles fine, 004 and 005 all fail. Would those be separate plates? Is there anything particular about those plates? Are they different in some way? If you could give me as much detail about the samples as possible it would be very helpful, as I will then be better able to communicate with the Tracy team.

**Comment by blex-max** [comment]
bug confirmed - I can reproduce this but only if I use the pipeline, not if I use Tracy alone...

**Comment by blex-max** [comment]
@helena-shapton `git pull` and give it a try now

**Comment by blex-max** [comment]
@helena-shapton fixed? If you haven't tried it yet, it's probably best to delete all previous output before running the command again just to be sure.

**Comment by helena-shapton** [comment]
Hi sorry I have been offline for Easter, I do not know how to delete previous outputs (i.e. what to delete and what not to). Git pull gave the following error:
error: Your local changes to the following files would be overwritten by merge:
        README.md
        scripts/quick_out_vsearch_results.py
        scripts/test_run.sh
Please commit your changes or stash them before you merge.
Aborting

Should I try to run the syntax steps on what I've got (i.e. plate 3) or not?

Re detail about the samples. Yes there are 3 different plates.
Plate 3- Pierceland Woodland (Broadleaf woodland)
Plate 4 Some Pierceland, mostly SSSI (Broadleaf with some conifers- largely mixed and unmanaged)
Plate 5- Christmas tree plantation (Highly dense monoculture of spruce)

**Comment by helena-shapton** [comment]
I will try and reply as much as possible but I likely won't be online until tomorrow afternoon as I have a flight in the morning.

**Comment by blex-max** [comment]
No worries, I'm trying to work quickly only because I'm aware you have limited time. My fix makes those files run successfully on my end.

With regard to deleting previous outputs - I just mean everything in the output directory you're specifying with -o, all the output results/data from the pipeline.

The error is telling you what the issue is, but the quick solution is `git reset --hard` then `git pull`.

I need to test the second stage of the pipeline as I am just about done wrapping it up into a single command. I'll try and get that finished tomorrow.

Thanks, that is good to know. Any differences in how you processed them, particularly with regard to the sequencer?

**Comment by helena-shapton** [comment]
Yes plate 3 is all running great now, just the other two with assembly failures. I did not process these so I can ask Jim but the sequencing should have been the same. Tell me when the second stage is ready to run. What about the command you gave me for it two weeks ago? (vsearch --sintax '~/its/cat_its.fa' \
--db 'PATH_TO_UNITE_DATABASE' \
--sintax_cutoff 0.8 \
--tabbedout '~')

Also related to this what is the path to the online database?

**Comment by blex-max** [comment]
Are you saying you have updated and the other two still aren't working? This is odd, as I can get the sample files to run successfully on my end. The second stage is now ready, though there will be changes to neaten the output in future. The command I gave you will still work.

You need to download whichever database you intend to use as a reference locally. I suggest you talk to Jim as I don't know which database you want to use.

**Comment by helena-shapton** [comment]
![image](https://user-images.githubusercontent.com/66360941/164421746-4167010d-2dda-462c-ad2b-46f613c136d0.png)
Yes still having issues

**Comment by blex-max** [comment]
I can see you did git reset and pull after having those issues - had you not already done it? If not, please run the pipeline after the pull! Otherwise you won't have the updates.

If it's still not working, I'll need you to share all your trace files with me. They'll be too big for github I think so perhaps via OneDrive.

**Comment by helena-shapton** [comment]
No i just did it after to show that its already fully updates- it's still not working. I'll email you everything

**Comment by helena-shapton** [comment]
I will ask Jim but I'm not sure he'll know what he wants to use so I am proposing using the massBLASTer and/or PROTAX-fungi for the initial IDing and then the SH matching for the de novo identification after- thoughts?

Advanced Analyses
SH matching - stand alone tool for UNITE Species Hypothesis matching and discovery of new fungal species from eDNA, specimens and other samples.
Code available on GitHub (https://github.com/TU-NHM/sh_matching_pub).
ITSx - stand alone software for detecting and extracting ribosomal ITS sequence regions of fungi and other eukaryotes for use in environmental sequencing (https://microbiology.se/software/itsx/).
Code available on GitHub (https://github.com/TU-NHM/itsx_plutof_pub).
PROTAX-fungi - stand alone tool for probabilistic taxonomic placement of fungal ITS sequences (https://github.com/psomervuo/protaxfungi).
Code available on GitHub (https://github.com/TU-NHM/protax_fungi_plutof_pub).
massBLASTer - a megablast utility for batch BLAST analysis of multiple query sequences against custom ribosomal ITS sequence datasets, script and BLAST databases.
Code available on GitHub (https://github.com/TU-NHM/massblaster_plutof_pub).

**Comment by blex-max** [comment]
I can't reproduce this bug on my end. All sequences run fine here. I suggest deleting the pipeline, all output, and cloning the repository again from scratch. Something's awry in there somehow, or it's an issue with Tracy itself. 

As for the question about databasing - the things you've linked are other tools for IDing sequences; the second stage of the pipeline does what those various tools intend to do using the sintax classification algorithm - it's just a question of what reference you use with it. I use the UNITE database for example. But that's moving off topic for a GitHub Issue so please email me if you want to discuss that more.

**Comment by blex-max** [comment]
@helena-shapton any updates on this?

**Comment by helena-shapton** [comment]
Sorry I was away on a training camp with rowing. No I can't get the other plates to run at all, but I did get plate 3 all done and unfortunately the efficacy was very low with just 7 out of 96 samples identifying and some to very low orders so I think I may look into running with a lower similarity requirement of 85% as opposed to the 97%, do you think this will give me more to work with?

**Comment by helena-shapton** [comment]
I believe this is the issue
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()

**Comment by blex-max** [comment]
No worries, there is no rush. Unfortunately you're not giving me enough information to help you in a timely manner. Did you delete + reinstall? What else have you tried, perhaps different sample names? I know what the error is, but as I say it's not reproducible on other systems, which means its a problem with your specific install as opposed to anything on my end. That's not to say I won't continue to try to help but please help me out!

As for the efficacy of the identification; please don't use the issue thread to ask unrelated questions. Since it is not a bug, please open a discussion on the discussion tab, and include the relevant output files and the commands you used to get there. I do have comments but I won't go into them on this thread.

**Comment by helena-shapton** [comment]
Are you available to call on teams about this today? I will email also I am sorry if this is the wrong thread to say that.
